### ISSUE TITLE
Error launching osh-base version - Error in module 'Weather Data Storage' , 'GPS Sensor Storage'

### ISSUE THREAD

**Issue by ch08532** [opensensorhub/osh-distros#2]
Attempting to launch the osh-base and getting errors cannot find db/gps_obs.dat and db/weather_obs.dat.  Compiled osh-core, sensors, comm and distro without issue.

Output of the launch script is attached and linked below:

[output.log](https://github.com/opensensorhub/osh-distros/files/628163/out.txt)

The admin web application does work and can be accessed however the GPS Sensor and Weather Data Storage items are STOPPED and showing the error. 

Can't seem to find the .dat files.  Do I need to build anything else to generate the dat files?

--

RESOLUTION:

I ended  up copying the db folder from within the release .zip, placed them in the main snapshot folder.  Need to define/describe where to grab the .dat files in the readme.

**Comment by alexrobin** [comment]
'db' folder is now created automatically
